name: Daily Tweet Scheduler

on:
  schedule:
    - cron: '40 07 * * *'  # Queue early at 7:45 AM UTC (runs up to 10 min late)
  workflow_dispatch:        # Manual trigger support

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Check secrets (you can keep or remove this once tested)
      - name: Debug: Check if secrets are available
        run: |
          echo "Checking if secrets are available..."
          for var in API_KEY BEARER_TOKEN API_SECRET_KEY ACCESS_TOKEN ACCESS_TOKEN_SECRET; do
            if [ -z "${{ secrets[$var] }}" ]; then
              echo "$var is NOT set"
            else
              echo "$var is set"
            fi
          done

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 🕒 Wait until exactly 8:00 AM UTC
      - name: Wait until 8:00 AM UTC
        run: |
          target=$(date -d '08:00 UTC' +%s)
          now=$(date -u +%s)
          sleep_seconds=$(( target - now ))
          if [ $sleep_seconds -gt 0 ]; then
            echo "Waiting $sleep_seconds seconds until 8:00 AM UTC..."
            sleep $sleep_seconds
          else
            echo "It's already past 8:00 AM UTC, continuing immediately."
          fi

      - name: Run tweet script
        run: python root_stokes.py
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
